services:
  tor:
    container_name: tor-service
    build: ./tor/
    depends_on:
      - nginx-service
    networks:
      - tor-net

  nginx:
    container_name: nginx-service
    build: ./nginx/
    expose:
      - "80"
      - "22"
    networks:
      - tor-net

networks:
  tor-net:
    driver: bridge
